<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [1]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

## 1.2 Arrays only | Subsetting by masking

In [5]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [6]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

In [8]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_array[(np_array > 3) & (np_array < 8)] # '&' means 'AND'

array([4, 5, 6, 7])

In [9]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_array[(np_array < 3) | (np_array > 8)] # '|' means 'OR'

array([ 1,  2,  9, 10])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [11]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)
py_list_2d[3]

[4, 'D']

In [16]:
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

In [14]:
py_list_2d[3][0]

4

In [15]:
np_array_2d[3, 0]

'4'

In [17]:
py_list_2d[:3][0]

[1, 'A']

In [18]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

In [19]:
py_list_2d[3:6][0]

[4, 'D']

In [20]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U11')

In [21]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

## 1.4 Growing lists

In [22]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [24]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [25]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [26]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [27]:
x = [1, 2, 3]
x += [4, 5, 6]
x

[1, 2, 3, 4, 5, 6]

In [29]:
x=[1, 2, 3]
x.extend([4, 5, 6])
x

[1, 2, 3, 4, 5, 6]

In [28]:
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [31]:
a=(1, 2, 3)     # Define tuple
print(a[0])    # Access data

1


In [32]:
# The following will NOT work
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [ ]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [ ]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes

The gains in speed are due to NumPy doing things to all the elements in the array in one go. For this, the data needs to be stored in a specific order in memory. Adding or removing elements hinders this optimization. When you change the size of a NumPy array, NumPy destroys the existing array and creates a new one, making it extremely inefficien