<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

It is important to understantd how to store, retrieve and modify data in programming. This is because these abstract structures will influence how you think about data. 

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

**Python List**

In [ ]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

**Numpy Array**

In [ ]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

**Dictionary**

In [ ]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

Dictionaries use a key and an associated value separated by a :

The dictionary very elegantly holds the real and superhero names in one structure while we need two lists (or arrays) for the same data.

For lists and arrays, the order matters. I.e. ‘Natasha Romanoff’ must be in the same position as ‘Black Widow’ for things to work.

**Basic Way of Storing data:**

1. List

2. Numpy arrays

3. Dictionary

## 1.2 Accessing data from a list (or array)

 The image below shows the relationship between the position and index:



![](https://sps.nus.edu.sg/sp2273/docs/python_basics/03_storing-data/python-zero-indexed-counting.png)

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
py_real_names[0]

'Natasha Romanoff'

In [4]:
py_super_names[0]

'Black Widow'

In [5]:
py_super_names[2]    # Forward indexing 
                     # We need to know the size 
                     # beforehand for this to work.

'Doctor Strange'

In [6]:
py_super_names[-1]   # Reverse indexing

'Doctor Strange'

## 1.3 Accessing data from a dictionary

In [2]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  
superhero_info["Natasha Romanoff"]

'Doctor Strange'

In [3]:
superhero_info['Stephen Strange']

'Doctor Strange'

In [4]:
#superhero_info["Doctor Strange"] cannot assess key

KeyError: 'Doctor Strange'

dictionaries have a key-value structure.

## 1.4 Higher dimensional lists

Can think of it as 2D list (can be 3D or more)

In [ ]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [5]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array
len(py_list_2d)

10

In [6]:
len(np_array_2d)

10

In [7]:
np_array_2d.shape

(10, 2)

numpy shape function also give you the size of the list inside the list

## 2.2 Arrays are fussy about type

In [8]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)
py_list

[1, 1.5, 'A']

In [9]:
np_array

array(['1', '1.5', 'A'], dtype='<U32')

array convert the numbers into string

numpy tolerates only a single type

## 2.3 Adding a number

In [12]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
np_array + 10

array([11, 12, 13, 14, 15])

In [13]:
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [14]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)
py_list_1 + py_list_2       #add a list to a another list

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [15]:
np_array_1 + np_array_2     #add the contents of the list to the contents of another list

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [16]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
py_list*2                 #same as adding another list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [17]:
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [18]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
np_array**2         #this works the same as addition and multiplication

array([ 1,  4,  9, 16, 25])

In [19]:
py_list**2                      # Won't work!  

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

## 2.7 Asking questions

In [20]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
py_list == 3     # Works, but what IS the question?

False

In [23]:
py_list > 3      # Won't work!

TypeError: '>' not supported between instances of 'list' and 'int'

In [21]:
np_array == 3   #ask a question to the array

array([False, False,  True, False, False])

In [22]:
np_array > 3 

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [25]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
sum(py_list)     # sum() is a base Python function

15

In [26]:
max(py_list)     # max() is a base Python function

5

In [27]:
min(py_list)     # min() is a base Python function

1

In [28]:
np_array.sum()

15

In [29]:
np_array.max()

5

In [30]:
np_array.min()

1

In [31]:
np_array.mean()

3.0

In [32]:
np_array.std()

1.4142135623730951

# Exercises & Self-Assessment

In [ ]:



# Your solution here




## Footnotes